### PR TITLE
Left-right keys work for non-consecutive pairs of bells

### LINKED ISSUE #140: Allow people to ring non-adjacent bell pairs
Currently, ringing the left and right 'hand' bells will always ring the two bells at the bottom of the screen.  However, it would be nice to be able to ring more obscure pairs of bells, like `1` and `3` without having to resort to using the number keys.

If this change is approved (I'm working on a PR for this), then I think we should make left and right always go round the circle the shortest way - so if the `treble` and `tenor` are assigned, then the tenor will be the `left` hand and the treble the `right`.  The easiest implementation would be to have `left` always refer to the numerically lowest bell, which would cause potential jankiness in situations like this, so something slightly more advanced is needed I think.

@lelandpaul, @BrynMarieR, please could you reply to this with a yes or no before I spend too much time on the code for it - cheers!

### PR DESCRIPTION
**Pull request by Kneasle**
Closes #140.

This now has 4 cases to decide which bells should be assigned to the `left` and `right` keys:

**Case 1** - _no_ bells are assigned to the current user:
- Use the current behaviour of ringing the two bells at the bottom of the screen

**Case 2** - _1_ bell is assigned to the current user:
- This bell will be the `right` hand bell, and the `left` hand key will do nothing.  This is the only really user-noticeable change from this PR, but I think it makes more sense than the `left` key potentially ringing a bell assigned to someone else.

**Case 3** -  _2_ bells are assigned to the current user:
- These two bells will be assigned to the `left` and `right` keys, regardless of whether or not they are next to each other and how the user's view is aligned.  It will always assign them as though the user is sitting between them (going the shortest distance round the circle).  Therefore, if the `1` and `8` are assigned (for ringing `Major`), then the `right` key will ring the `8` and the `left` key will ring the `1`.

**Case 4** - _more than 2_ bells are assigned to the current user:
- The `right` key will ring the numerically lowest of these bells, and the `left` key will ring the second numerically lowest of these bells.  I don't expect this to happen very much since there are only two keys to ring bells from, but in case it does it's quite badly defined how to assign them - so I've gone with this solution on the basis that it's easy to implement and understand.

### CODE REVIEW

**Comment by BrynMarieR** [comment]
Just a thought about case 3:

In my experience, if a ringer is ringing the 1 and 8, the 1 stays in the ringer's right hand and the 8 stays in the ringer's left hand; ie, the rule is "the lowest numbered bell goes in the right hand, and the other bell goes in the left".

In addition, if you are assigned to the 1,8 pair in RR, the circle rotates to put the lowest numbered bell in the right-hand position. 

@lelandpaul  what do you think?

**Comment by Kneasle** [comment]
I did consider this - the code is also significantly more compact and elegant if use that rule (since the last 3 cases all collapse into one).  However, it's really difficult to ring the treble and tenor like that (on the basis that the bells are either the wrong way round or on the wrong side of the circle).  Also, I suspect that ringing tenor-treble would be the most likely use case of this.

I also considered updating the code that sets the tower rotation, but I wanted this to be only noticeable to the people who actually want to use it and having the tower rotate seemingly randomly would not really work like that.  However, if you guys think it would be better, I'm happy to do that.

**Comment by BrynMarieR** [comment]
Ok, we've conferred and you're right -- I think this way is simpler + better. We're creating a new branch for the next release and this PR will be merged with that branch. Thanks!

**Comment by Kneasle** [comment]
Cool cheers!

**Pull request merged**
